version: "3"

services:
  ansible:
    image: ansibleimage
    container_name: ansible-controller
    volumes:
      - .:/ansible
      - ~/.ssh:/root/.ssh:ro
      - .vagrant:/root/.vagrant:rw
    working_dir: /ansible
    stdin_open: true
    tty: true