# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  # Désactiver le partage de dossier inutile
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Définir les machines avec leurs IPs
  machines = {
    "laptop" => "192.168.60.2",
    "switch" => "192.168.60.3",
    "router" => "192.168.60.4"
  }

  machines.each do |name, ip|
    config.vm.define name do |vm|
      vm.vm.hostname = name

      vm.vm.network "private_network",
        ip: ip,
        netmask: "255.255.255.0",
        type: "hostonly"

      vm.vm.provider "virtualbox" do |vb|
        vb.name = name
        vb.memory = 1024
        vb.cpus = 1
      end
    end
  end
end
