version: '3.8'

services:
  ldap-server:
    image: osixia/openldap:1.5.0
    container_name: ldap-server
    environment:
      - LDAP_ORGANISATION=VivoEnergy
      - LDAP_DOMAIN=example.com
      - LDAP_ADMIN_PASSWORD=admin
    ports:
      - "389:389"
      - "636:636"
    networks:
      - ldap_net

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap-server
      - PHPLDAPADMIN_HTTPS=false
    ports:
      - "8181:80"
    depends_on:
      - ldap-server
    networks:
      - ldap_net

networks:
  ldap_net:
    driver: bridge
