global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'snmp'
    metrics_path: /snmp
    params:
      module: [if_mib]  # correspond à ce qui est défini dans snmp.yml
    static_configs:
      - targets:
          - 192.168.60.2
          - 192.168.60.3
          - 192.168.60.4  # ← l’adresse IP de ton snmp_exporter
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter:9116  # ← port exposé de ton snmp_exporter

        
  - job_name: 'ping'
    static_configs:
      - targets: ['ping-exporter:9427']